/*
 * This script checks whether the arduino board is able to capture the voltage signals generated by the piezos
 * 
 * By:
 *    Jash Bharat Mota
 *     jash@lyflime.com
 *    http://www.jashmota.esy.es
 */

// these constants won't change:
const int knockSensor = A1; // the piezo is connected to analog pin 0


// these variables will change:
int sensorReading = 0;      // variable to store the value read from the sensor pin

void setup() {
  Serial.begin(9600);       // use the serial port
}

void loop() {
  // read the sensor and store it in the variable sensorReading:
  sensorReading = analogRead(knockSensor);

  delay(200);  // delay to avoid overloading the serial port buffer
  Serial.print("Voltage: ");
  Serial.println(sensorReading);
}

